In [1]:
# Distance Analysis
# 25m 45m 65m

In [28]:
from sklearn.preprocessing import scale, robust_scale, minmax_scale, maxabs_scale
from sklearn.model_selection import train_test_split
from sklearn.externals import joblib
import numpy as np
import glob
import librosa

In [46]:
# Load Model
model = joblib.load("10252018_randomforest_bee2drone_n_sc.pkl")

In [47]:
# Load Data
#drone_path = "/Users/junhyuckwoo/capstone/TestFile/ProceedData/phantom2_44100_1s/*.wav"
drone_path = "/Users/junhyuckwoo/capstone/TestFile/Data/DistanceTest/Syma/*.wav"
drone_files = glob.glob(drone_path)
drone_files.sort()

In [48]:
# Test Data - 15m
data,sr = librosa.load(drone_files[0], sr=44100)
norm = maxabs_scale(data[:44100])
drone = librosa.feature.spectral_contrast(norm).T
drone.shape

(87, 7)

In [49]:
y_d = np.ones(len(drone))
y_d.shape

(87,)

In [50]:
prediction = model.predict(drone)
from sklearn.metrics import precision_recall_fscore_support
p,r,f,s = precision_recall_fscore_support(y_d, prediction, average='micro')
print("Model: 10282018_randomforest_bee2drone_n_sc.pkl")
print("F-Score:", round(f,3))
from sklearn.metrics import accuracy_score
print("Accuracy: ", accuracy_score(y_d, prediction))
from sklearn.metrics import classification_report
print(classification_report(y_d, prediction))
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_d, prediction))

Model: 10282018_randomforest_bee2drone_n_sc.pkl
F-Score: 0.989
Accuracy:  0.9885057471264368
             precision    recall  f1-score   support

        0.0       0.00      0.00      0.00         0
        1.0       1.00      0.99      0.99        87

avg / total       1.00      0.99      0.99        87

[[ 0  0]
 [ 1 86]]


/Users/junhyuckwoo/capstone/lib/python3.5/site-packages/sklearn/metrics/classification.py:1137: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


In [51]:
# Test Data - 25m
data,sr = librosa.load(drone_files[1], sr=44100)
norm = maxabs_scale(data[:44100])
drone = librosa.feature.spectral_contrast(norm).T
drone.shape

(87, 7)

In [52]:
prediction = model.predict(drone)
from sklearn.metrics import precision_recall_fscore_support
p,r,f,s = precision_recall_fscore_support(y_d, prediction, average='micro')
print("Model: 10282018_randomforest_bee2drone_n_sc.pkl")
print("F-Score:", round(f,3))
from sklearn.metrics import accuracy_score
print("Accuracy: ", accuracy_score(y_d, prediction))
from sklearn.metrics import classification_report
print(classification_report(y_d, prediction))
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_d, prediction))

Model: 10282018_randomforest_bee2drone_n_sc.pkl
F-Score: 0.885
Accuracy:  0.8850574712643678
             precision    recall  f1-score   support

        0.0       0.00      0.00      0.00         0
        1.0       1.00      0.89      0.94        87

avg / total       1.00      0.89      0.94        87

[[ 0  0]
 [10 77]]


/Users/junhyuckwoo/capstone/lib/python3.5/site-packages/sklearn/metrics/classification.py:1137: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


In [53]:
# Test Data - 45m
data,sr = librosa.load(drone_files[2], sr=44100)
norm = maxabs_scale(data[:44100])
drone = librosa.feature.spectral_contrast(norm).T
drone.shape

(87, 7)

In [54]:
prediction = model.predict(drone)
from sklearn.metrics import precision_recall_fscore_support
p,r,f,s = precision_recall_fscore_support(y_d, prediction, average='micro')
print("Model: 10282018_randomforest_bee2drone_n_sc.pkl")
print("F-Score:", round(f,3))
from sklearn.metrics import accuracy_score
print("Accuracy: ", accuracy_score(y_d, prediction))
from sklearn.metrics import classification_report
print(classification_report(y_d, prediction))
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_d, prediction))

Model: 10282018_randomforest_bee2drone_n_sc.pkl
F-Score: 0.115
Accuracy:  0.11494252873563218
             precision    recall  f1-score   support

        0.0       0.00      0.00      0.00         0
        1.0       1.00      0.11      0.21        87

avg / total       1.00      0.11      0.21        87

[[ 0  0]
 [77 10]]


/Users/junhyuckwoo/capstone/lib/python3.5/site-packages/sklearn/metrics/classification.py:1137: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


In [55]:
# Test Data - 65m
data,sr = librosa.load(drone_files[3], sr=44100)
norm = maxabs_scale(data[:44100])
drone = librosa.feature.spectral_contrast(norm).T
drone.shape

(87, 7)

In [56]:
prediction = model.predict(drone)
from sklearn.metrics import precision_recall_fscore_support
p,r,f,s = precision_recall_fscore_support(y_d, prediction, average='micro')
print("Model: 10282018_randomforest_bee2drone_n_sc.pkl")
print("F-Score:", round(f,3))
from sklearn.metrics import accuracy_score
print("Accuracy: ", accuracy_score(y_d, prediction))
from sklearn.metrics import classification_report
print(classification_report(y_d, prediction))
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_d, prediction))

Model: 10282018_randomforest_bee2drone_n_sc.pkl
F-Score: 0.046
Accuracy:  0.04597701149425287
             precision    recall  f1-score   support

        0.0       0.00      0.00      0.00         0
        1.0       1.00      0.05      0.09        87

avg / total       1.00      0.05      0.09        87

[[ 0  0]
 [83  4]]


/Users/junhyuckwoo/capstone/lib/python3.5/site-packages/sklearn/metrics/classification.py:1137: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
